### ISSUE TITLE
UI - Product Detail

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/abexsun#1]
a) when user try to add item into "Cart" use validation , user sh'd select at least 1 color and 1 size.1 **RFR**

**Comment by serviceproviderpk** [comment]
On product detail show following information ref url:https://www.shein.co.uk/Batwing-Sleeve-Pocket-Side-Curved-Hem-Textured-Dress-p-475166-cat-1889.html

b) SKU: it will be product id
c) show Rating
d) on product detail page Show Size Guide
for this we will add new table
"SizeGuide:SizeGuideId,CategoryID,Description,HowToMeasureDescripton,SizeImage
value for CM/Inch we will show in editor box
e) in SizeCtegoryTable add new filed "ToolTip" as user will mouse hover on producct detail page
we will show text as below
![image](https://user-images.githubusercontent.com/19146254/41010701-831f1ef8-6952-11e8-9ff9-b18dc2097397.png)
f) In product table add following filed in admin section tab and on product detail tab
1) Size_Fit
2) Delivery
3) Return Policy
data type of each field will be"nvarchar(max)
ref: 
![image](https://user-images.githubusercontent.com/19146254/41010759-e113dd28-6952-11e8-9880-e0d38d46c67c.png)
https://www.shein.co.uk/Batwing-Sleeve-Pocket-Side-Curved-Hem-Textured-Dress-p-475166-cat-1889.html
g) on product detail page above the below section
![image](https://user-images.githubusercontent.com/19146254/41010803-189b155e-6953-11e8-802c-000aa6631b2c.png)

and another section give it name "Customers Also Viewed"
to manage it "Create a new table"
"MostlyViewed:Id,ProductId,ViewDateTime, when user view any product we will do an entry in it.
and on detail page we will show those products, whose were viewed.

**Comment by adilshehbaz** [comment]
Use Category Table Add New Field with named SizeGuid(nvarchar(max));
