### ISSUE TITLE
Product - Add Size

### ISSUE THREAD

**Issue by usmanfarooq05** [serviceproviderpk/abexsun#11]
There is an error on saving product size.
![image](https://user-images.githubusercontent.com/25413143/40886073-0ddd5dca-674b-11e8-8fe2-887310fb4711.png)
![image](https://user-images.githubusercontent.com/25413143/40886080-2564500c-674b-11e8-8ba6-d7a979dfd13a.png)

**Comment by serviceproviderpk** [comment]
Fixed
