### ISSUE TITLE
Internal Feedback

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/abexsun#41]
)
) In color list (/Dashboard/Color/Index/) add one more column
and show color as well as
) as we flush the db also remove all images of products and categorys
then check in code
it will reduce size of project

) @adil Stock Quanity not updating if i set Quanity for last 2 size
it sets 0
in stock list also show actaul color with color name

) in order detail  user entered detail is not correct
i see postal code,coutnry,city,address are diffrent , not same those were detected by
api and showed to the users

) if user is on "My Shopping cart" list if user click on product name
redirect user to product detail page
) i created an account , then i verified my email
then i login

i click on a product add item into shopping cart car and click on check out
Checkout info was not filled for my acccount

) in edit profile also use api to set user addess using postal code
we will remove drop down from edit profile
) product review , when customer will post reivew its status will be pending
and will not display on product detail page until it is approved

admin section we will show "Product Reviews" and "Pending Reviews"

i have added on review, review photo is missing ,although i have already
added photo in my profile

) Move "Enquiry and  Product Reviews" from "System User" to "Promotions "
) in Add produt set default "Warehouse" as Yooslay
) in all email tempates  replace following text

 Thankyou
By YooSlay Team

with

Thanks,
YooSlay

**Comment by serviceproviderpk** [comment]
8) set session variable value from SessionItemKeys
9) Country pronvice city proper label , right now its showing category as lable
.

**Comment by serviceproviderpk** [comment]
11) recently viewed on top

**Comment by serviceproviderpk** [comment]
12) On product list page
Show "Popular Products and category"
Color and size shd' show data as we select any category

**Comment by serviceproviderpk** [comment]
(1 &2) In progress

**Comment by khalidjavaid** [comment]
(2) Fixed
(5) Fixed
(6) Fixed
(7) Fixed

**Comment by serviceproviderpk** [comment]
@adilshehbaz @khalidjavaid  feedback is updated.

**Comment by serviceproviderpk** [comment]
11) in admin dasbhoard if i click on cancel button of order detail , i am getting error
![image](https://user-images.githubusercontent.com/19146254/42067964-8dc1a796-7b62-11e8-87cb-2254dff10d39.png)
![image](https://user-images.githubusercontent.com/19146254/42067969-9b87b58c-7b62-11e8-9de9-c1fc9d18d5db.png)

**Comment by serviceproviderpk** [comment]
12) Rename menu "Customers" to "System Users" and at the end of this menu add two more sub menu
a) Admins (show list of admin)
b) Editor (Show list of Editors)
Admin sh'd be able to add/edit admins and editors

**Comment by serviceproviderpk** [comment]
13) Change email template for  change password, as i given as email

**Comment by serviceproviderpk** [comment]
14) on Quick view, it always says, chooose color
15) on quick view "Add to cart" "Check out"  are touching and not aligned properly.

**Comment by serviceproviderpk** [comment]
16) Admin sh'd be able to add/edit "admin and Editor" accounts

**Comment by serviceproviderpk** [comment]
17 ) remove "Enqyiur" and product reviews from "System Users"
18 ) change location at bottom
check add/edit buttons

**Comment by serviceproviderpk** [comment]
14) Fixed

**Comment by serviceproviderpk** [comment]
15) Product Detail  image not change if user choose any image from product images
16 )add to cart not working on detail page
17 ) on Quick view Quntity is not changing

**Comment by serviceproviderpk** [comment]
18 ) Use cache in country and provice list

**Comment by serviceproviderpk** [comment]
18) latest feedback
[YooSlay_WebTasklist.xlsx](https://github.com/serviceproviderpk/abexsun/files/2153058/YooSlay_WebTasklist.xlsx)

**Comment by serviceproviderpk** [comment]
19) in grid, where are showing price remove the space between currency symbol
and price, in admin also show symbol near price (right now are displaying in table heading)
20)  I have reduced the products but when we have many products and if we are in page 2 of products and then amend any thing there. it takes back to page 1 products. I think it should stay to page 2 products ?
21)Improve the formatting of order detail in "Print" view, use logo
and you can use someother theme like smartadmin etc.
22) on customer dashobard > order detail also show "Shipping Option" and insurence enable

![image](https://user-images.githubusercontent.com/19146254/42067246-a32475cc-7b5e-11e8-9174-de0f2561519a.png)

that was choosen from below option
![image](https://user-images.githubusercontent.com/19146254/42067277-c9a9be28-7b5e-11e8-98da-99fb7e34bcd1.png)

also display above information in order detail for "Admin Dasbhoard

**Comment by serviceproviderpk** [comment]
22) for these button 
![image](https://user-images.githubusercontent.com/19146254/42199965-a9fb3c88-7eaa-11e8-9391-5c1c2c21ed51.png)

use css of the current theme you can use shopping cart button css
like below button
![image](https://user-images.githubusercontent.com/19146254/42199980-bf88c688-7eaa-11e8-97c7-37fc02f8e1cd.png)

**Comment by serviceproviderpk** [comment]
25) On MakePayment/Index  Please show billing details
i see city is showing "1" instead of name of city, Please also check other information as well as.

this page will display billings Details

**Comment by serviceproviderpk** [comment]
25) on order detail show all details like Shippment charges, and insurence charges, check total amount is  correct.
![image](https://user-images.githubusercontent.com/19146254/42201223-4d149d06-7eb0-11e8-8dc8-bb2b5435b815.png)

**Comment by serviceproviderpk** [comment]
26) if user account is created we are sending this email

Dear Customer :         Your account is created , now you can buy items on the YooSlay portal, the Delivery charges within UK is free and will be charged as per weight for Nationwide . online Shopping cart platform for Local & Imported Products.User Name: fname lnamePassword: 123Email: service@serviceprovider.pkClick Here For Email Verify | Dear Customer :         Your account is created , now you can buy items on the YooSlay portal, the Delivery charges within UK is free and will be charged as per weight for Nationwide . online Shopping cart platform for Local & Imported Products.User Name: fname lnamePassword: 123Email: service@serviceprovider.pkClick Here For Email Verify | Dear Customer :         Your account is created , now you can buy items on the YooSlay portal, the Delivery charges within UK is free and will be charged as per weight for Nationwide . online Shopping cart platform for Local & Imported Products. | User Name: fname lnamePassword: 123Email: service@serviceprovider.pk |   | Click Here For Email Verify | Click Here For Email Verify
-- | -- | -- | -- | -- | -- | --
Dear Customer :         Your account is created , now you can buy items on the YooSlay portal, the Delivery charges within UK is free and will be charged as per weight for Nationwide . online Shopping cart platform for Local & Imported Products.User Name: fname lnamePassword: 123Email: service@serviceprovider.pkClick Here For Email Verify | Dear Customer :         Your account is created , now you can buy items on the YooSlay portal, the Delivery charges within UK is free and will be charged as per weight for Nationwide . online Shopping cart platform for Local & Imported Products. | User Name: fname lnamePassword: 123Email: service@serviceprovider.pk |   | Click Here For Email Verify | Click Here For Email Verify
Dear Customer :         Your account is created , now you can buy items on the YooSlay portal, the Delivery charges within UK is free and will be charged as per weight for Nationwide . online Shopping cart platform for Local & Imported Products.
User Name: fname lnamePassword: 123Email: service@serviceprovider.pk
 
Click Here For Email Verify | Click Here For Email Verify
Click Here For Email Verify
Copyright © 2018 YooSlay Shop, All rights reserved. Our mailing address is: info@yooslay.co.uk | Copyright © 2018 YooSlay Shop, All rights reserved. Our mailing address is: info@yooslay.co.uk | Copyright © 2018 YooSlay Shop, All rights reserved. Our mailing address is: info@yooslay.co.uk
Copyright © 2018 YooSlay Shop, All rights reserved. Our mailing address is: info@yooslay.co.uk | Copyright © 2018 YooSlay Shop, All rights reserved. Our mailing address is: info@yooslay.co.uk
Copyright © 2018 YooSlay Shop, All rights reserved. Our mailing address is: info@yooslay.co.uk



"show customer name" and in username show "username instead of contact name.

**Comment by serviceproviderpk** [comment]
[Yooslay.co.uk issues.docx](https://github.com/serviceproviderpk/abexsun/files/2163106/Yooslay.co.uk.issues.docx)

**Comment by serviceproviderpk** [comment]
![image](https://user-images.githubusercontent.com/19146254/42275852-14300a7e-7fab-11e8-99ce-ccde44b8631e.png)
add delivery option,

**Comment by serviceproviderpk** [comment]
) manage shipping option (add/edit)
) Clone option in category

**Comment by serviceproviderpk** [comment]
) show color and size in order detail of customer and admin dashboard

**Comment by serviceproviderpk** [comment]
) add delete button in "Static" page
when user click on it, set flag Delete=true, it will be hided form list page
and from front end sections

**Comment by serviceproviderpk** [comment]
) show list of product whose "Show in Menu" is true

**Comment by serviceproviderpk** [comment]
@adilshehbaz 

Create a new page "OrderShippment"

it will have following fields 

- ID
- OrderID
- TrackingNumber (string)
- TotalWeightValue(decimal)
- Total WeightUnit ( lb(s) | KG )
- DateShipped
- DateDeliverd
- AdminComments
- ShippmentMethodID
-ShipppedByUserID
Another Table
OrderShippmentItem ( will have following filed item will be fetched from orderdetail table)
ID
OrderShippmentId
ProductID
Quantity

For Refrence you can view http://admin-demo.nopcommerce.com/Admin/Order/ShipmentList

**Comment by adilshehbaz** [comment]
Find address by postal code using API on check out page RFR

**Comment by serviceproviderpk** [comment]
4) if i add multiple images for a product on "Quick view" it is display zig zag images.

**Comment by serviceproviderpk** [comment]
6) If user create an account from "Register page" on next page show below information.

Your account is successfully created, Please verify our email address to access our features"

**Comment by serviceproviderpk** [comment]
7) If user try to create an account with same email id show msg

"This email is already existing in our system, Please try with different email."
or click here if you forgot your password

as user will click on that link show him login page.

**Comment by serviceproviderpk** [comment]
8) in account creation email i am getting extra "_"
![image](https://user-images.githubusercontent.com/19146254/42533547-a3d500ec-84a3-11e8-9407-2a954092fe9b.png)
9) if user account is created using check out process also verification email.
i tried but didnot get email of  email verifications.

**Comment by serviceproviderpk** [comment]
9) on Quick view "Qunaity +- "button not working css of  alert box is not changed for it.
![image](https://user-images.githubusercontent.com/19146254/42533779-3fadf528-84a4-11e8-8294-2907f416351b.png)

**Comment by serviceproviderpk** [comment]
10) Shipment Feature (as i explained there sh'd be shipment menu, as user will ship an item
stock will be updated and email will be send to the customer
user will be able to track his "Order"
as item is shipped order status will be changed as well as

**Comment by serviceproviderpk** [comment]
11) From admin menu  hid "Location" menu, as we are not using these data right now.

**Comment by serviceproviderpk** [comment]
) on customer order "customer email is not displayed"
table is looking like zig zag you can use very thin border and proper allign
![image](https://user-images.githubusercontent.com/19146254/42614270-8b021458-85be-11e8-80f1-99c85096efe5.png)

we will use table only for order items
order will display with out table.

**Comment by khalidjavaid** [comment]
@ shippment update stoack as discussed

**Comment by khalidjavaid** [comment]
add last name  in  registration page

**Comment by serviceproviderpk** [comment]
@zaifullah786 
in admin dashobar in "Content menu"
add new link "Our Clients" and "Customer Reviews"
belw will be table name.

OurClients (Id,SerialNumber,Logo,CompnayName,ContactName,Email,Phone,Cell,Description,OtherDetails)
CustomerReviews(Id,SNO,Name,Email,Desinatin,Compnay,Comments,Rating(value from 1 to 5)
