### ISSUE TITLE
Employee Registration

### ISSUE THREAD

**Issue by adilshehbaz** [serviceproviderpk/abexsun#43]
1- Policy Option
2- Employ Code => How to make serial => How to change serial
3- Delete Employee
4- Delete Employee Type
5- Martial Status
6- Father / Husband Name
7- Employee right of Active, Probation Period
8- Employee Comments, Remarks, Document Uploading via scanner

**Comment by serviceproviderpk** [comment]
9) if  user change his password or new account created send email on sp.pk email id
With following info

1.  domain URL
2. Branch Name,
3. Email
4. Passowrd
