### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/abexsun#49]
1) "Do not take Digits in currency" can you please  explain it.
2) When In Product and the go back to the list, take you to the first page. It will be later

**Comment by zshah10** [comment]
1-  Product price should be in £00.00 ie; £9.99 at the moment we can do only £9.00
2- I have reduced the products but when we have many products and if we are in page 2 of products and then amend any thing there. it takes back to page 1 products. I think it should stay to page 2 products ?

**Comment by serviceproviderpk** [comment]
@zshah10  Thanks
