### ISSUE TITLE
If we don't have color of the product, It won't let checkout

### ISSUE THREAD

**Issue by adilshehbaz** [serviceproviderpk/abexsun#64]
![image](https://user-images.githubusercontent.com/28675602/43129738-85842d60-8f4e-11e8-933a-eedb53cef325.png)

**Comment by zaifullah786** [comment]
Because while adding new product, it is compulsory to have product color because if you dont add color you cannot add product quantity.

**Comment by adilshehbaz** [comment]
![image](https://user-images.githubusercontent.com/28675602/43134232-d244b8ac-8f5a-11e8-85b5-2c8fce09c255.png)
