### ISSUE TITLE
Yooslaywebsite

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/abexsun#77]
1) if we share home page, category page, detail page on face book it sh'd display image.
of selected product and category.

**Comment by serviceproviderpk** [comment]
2) in main menu add new menu after "Asian Slay"   On Sale
if user click on it, show list of products which are on discount prices

**Comment by adilshehbaz** [comment]
**1. Fixed**

**Comment by serviceproviderpk** [comment]
3) rename woman to women please
![image](https://user-images.githubusercontent.com/19146254/49195435-e6fa0380-f3a8-11e8-9020-cf084c29e33c.png)

**Comment by serviceproviderpk** [comment]
4) please fix following points
![image](https://user-images.githubusercontent.com/19146254/49195552-625bb500-f3a9-11e8-91a6-b282ba8c9114.png)

**Comment by adilshehbaz** [comment]
**3 Fixed**

**Comment by adilshehbaz** [comment]
**7 Fixed**

**Comment by adilshehbaz** [comment]
**5- Fixed**

**Comment by adilshehbaz** [comment]
**4 Fixed**

**Comment by adilshehbaz** [comment]
**2 Fixed**
